# Generated by Django 3.0.6 on 2020-05-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('pub_date', models.DateTimeField()),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
